[mypy]
ignore_errors = False
warn_unused_configs = True
warn_redundant_casts = True
ignore_missing_imports = False
disallow_untyped_defs = True
disallow_incomplete_defs = True

[mypy-cassandra.*]
ignore_missing_imports = True

[mypy-astropy.*]
ignore_missing_imports = True

[mypy-pandas.*]
ignore_missing_imports = True

[mypy-lsst.daf.*]
ignore_missing_imports = True

[mypy-lsst.obs.*]
ignore_missing_imports = True
