name: build_and_test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
        with:
          # Need to clone everything for the git tags.
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Update pip/wheel infrastructure
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip install --system wheel

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          uv pip install --system -r requirements.txt

      # We have two cores so we can speed up the testing with xdist
      - name: Install pytest packages
        shell: bash -l {0}
        run: |
          uv pip install --system pytest pytest-xdist pytest-cov

      - name: List installed packages
        shell: bash -l {0}
        run: |
          conda list
          pip list -v

      - name: Build and install
        shell: bash -l {0}
        run: |
          uv pip install --system -v --no-deps -e .

      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest -r a -v -n 3 --cov=lsst.dax.apdb_migrate --cov=tests --cov-report=xml --cov-report=term --cov-branch
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
